@server=http://localhost:3000
@createdHostId={{createHost.response.body.id}}

### List hosts
GET {{server}}/hosts

### List a host
GET {{server}}/hosts/1

### Create a new host
# @name createHost
POST {{server}}/hosts
Content-Type: application/json

{
  "name": "DNS Server",
  "address": "1.1.1.1"
}

### Update a host
PUT {{server}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.1"
}

### Delete a host
DELETE {{server}}/hosts/{{createdHostId}}
