@server=http://127.0.0.1:3000/api
@createdHostId={{createHost.response.body.id}}

### Create a Host
# @name createHost
POST {{server}}/hosts
Content-Type: application/json

{
  "name": "DNS Server",
  "address": "1.1.1.1",
  "tags": ["DNS"]
}

### Get All Hosts
GET {{server}}/hosts

### Get a Host by ID
GET {{server}}/hosts/{{createdHostId}}

### Update a Host by ID
PUT {{server}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.1",
  "tags": ["DNS", "Cloudflare"]
}

### Delete a Host by ID
DELETE {{server}}/hosts/{{createdHostId}}

### Create a ping
POST {{server}}/hosts/{{createdHostId}}/pings/3

### Read pings
GET {{server}}/hosts/{{createdHostId}}/pings

### Read pings
GET {{server}}/pings

### Read tags
GET {{server}}/tags

### Read hosts by tag
GET {{server}}/tags/dns/hosts

### Create User
# @name createdUser
POST {{server}}/users
Content-Type: application/json

{
  "name": "Luiz",
  "email": "luiz@email.com",
  "password": "123"
}

### Create a user with same email
POST {{server}}/users
Content-Type: application/json

{
  "name": "Luiz",
  "email": "luiz@email.com",
  "password": "123"
}

### Create a user without email
POST {{server}}/users
Content-Type: application/json

{
  "name": "Luiz",
  "password": "123"
}
