@server=http://127.0.0.1:3000/api
@createdHostId={{createHost.response.body.id}}

### Create a Host
# @name createHost
POST {{server}}/hosts
Content-Type: application/json

{
  "name": "DNS Server",
  "address": "1.1.1.1"
}

### Get All Hosts
GET {{server}}/hosts

### Get a Host by ID
GET {{server}}/hosts/{{createdHostId}}

### Update a Host by ID
PUT {{server}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.1"
}

### Delete a Host by ID
DELETE {{server}}/hosts/{{createdHostId}}

### Create Ping Request with Host Parameter (Default Count: 3)

POST {{server}}/ping/1.1.1.1

### Create Ping Request with error

POST {{server}}/ping/300.8.8.8

### Create Ping Request with Host and Count Parameter

POST {{server}}/ping/1.1.1.1/count/1

